services:
  mcp-rs:
    container_name: mcp-rs
    build: .
    ports:
      - "${MCP_PORT:-3000}:3000"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    environment:
      - BASE_URL=${BASE_URL}
      - SEARXNG_URL=${SEARXNG_URL}
